# existing
VIA_ENABLE = yes
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = yes

# add for dual pointing
POINTING_DEVICE_ENABLE = yes
PMW3360_ENABLE = yes
CIRQUE_ENABLE = yes

I2C_ENABLE = yes
SPLIT_POINTING_ENABLE = yes
